dashboard/urls.py
from django.conf.urls import url
from django.conf.urls import include
from rest_framework import routers

from .views import home
from .views import panel 
from .views import get_id_data
from .views import about 
from .views import feedback
from .views import contact
from .views import more_information_view
from .views import search_ajax
from .views import ObjectInfoViewSet
from .views import MunicipalityViewSet
from .views import LocalityViewSet
from .views import CategoryTypeViewSet
from .views import ObjectTypeViewSet
from .views import SpeciesViewSet
from .views import ImageViewSet


router = routers.DefaultRouter()
router.register(r'objects', ObjectInfoViewSet)
router.register(r'municipalities', MunicipalityViewSet)
router.register(r'localities', LocalityViewSet)
router.register(r'category_types', CategoryTypeViewSet)
router.register(r'object_types', ObjectTypeViewSet)
router.register(r'species', SpeciesViewSet)
router.register(r'images', ImageViewSet)


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^panel/$', panel, name='panel'),
    url(r'^get_id_data/$', get_id_data, name='get_id_data'),
    url(r'^more_information/(?P<id>\d+)/$', more_information_view, name='more_information'),
    url(r'^search_ajax_function/?$', search_ajax, name='search_ajax'),
    url(r'^about/', about, name='about'),
    url(r'^objects/(?P<id>\d+)/$', more_information_view, name='more_information'),
    url(r'^contact/(?P<id>\d+)/$', contact, name='contact'),    
    url(r'^feedback/', feedback, name='feedback'),
    # REST
    url(r'^api/', include(router.urls)),
    

]

excelpars/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('dashboard.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)




dashboard/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from transliterate import translit
import uuid
from smart_selects.db_fields import ChainedForeignKey
from django.utils.safestring import mark_safe

def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return '{}/{}'.format(instance.slug, filename)


def create_object_info_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(instance.nativeName, 'ru', reversed=True))
        instance.slug = slug + '-'+uuid.uuid4().hex
        print(instance.slug)







class ObjectType(models.Model):
    class Meta:
        verbose_name = 'Тип объектов'
        verbose_name_plural = 'Типы объектов'
    
    name = models.CharField(
        max_length=200,
        verbose_name='Тип объекта',
    )
 
    def __str__(self):
        return self.name


class CategoryType(models.Model):
    class Meta:
        verbose_name = 'Категория объектов'
        verbose_name_plural = 'Категории объектов'
    
    name = models.CharField(
        max_length=200,
        verbose_name='Категория объекта'
    )
 
    def __str__(self):
        return self.name


class Municipality(models.Model):
    
    class Meta:
        verbose_name = 'Муниципальное образование'
        verbose_name_plural = 'Муниципальные образования'
        ordering = ('name', )

    name = models.CharField(
        max_length=200,
        verbose_name='Муниципальное образование'
    )

    def __str__(self):
        return self.name


class Locality(models.Model):

    class Meta:
        verbose_name = 'Населенный пункт'
        verbose_name_plural = 'Населенные пункты'
        ordering = ('name',)

    name = models.CharField(
        verbose_name='Населенный пункт',
        max_length=200
    )

    municipality = models.ForeignKey(
        'Municipality',
        verbose_name='Муниципальное образование',
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )
    
    def __str__(self):
        return self.name


class Species(models.Model):

    class Meta:
        verbose_name = 'Видовая принадлежность'
        verbose_name_plural = 'Видовые принадлежности'

    name = models.CharField(
        verbose_name='Общая видовая принадлежность',
        max_length=200
    )
    
    def __str__(self):
        return self.name


class ObjectInfo(models.Model):

    class Meta:
        verbose_name = 'Объект'
        verbose_name_plural = 'Объекты'

    slug = models.SlugField(
        verbose_name='slugURL',
        max_length=400,
        null=True,
        blank=True
    )

    id_openData = models.CharField(
        max_length=200, 
        verbose_name='ID opendata.mkrf.ru',
        blank=True,
        null=True)

    nativeName = models.CharField(
        max_length=200,
        verbose_name='Наименование',
        blank=True,
        null=True
    )
    fullAddress = models.TextField(
        verbose_name='Полный адрес',
        blank=True,
        null=True
    )


    coordinates = models.CharField(
        max_length=200,
        verbose_name = 'Координаты',
        blank=True,
        null=True
    )

    photo_url = models.CharField(
        max_length=500,
        verbose_name = 'URL фото',
        blank=True,
        null=True
    )

    create_date = models.CharField(
        max_length=100,
        verbose_name = 'Дата создания',
        blank=True,
        null=True
    )

    object_type = models.ForeignKey(
        ObjectType,
        on_delete=models.SET_NULL,
        verbose_name='Тип объекта',
        blank=True,
        null=True
    )


    category_type = models.ForeignKey(
        CategoryType,
        on_delete=models.SET_NULL,
        verbose_name='Категория объекта',
        blank=True,
        null=True
    )

    reg_number = models.CharField(
        max_length=100,
        verbose_name='Регистрационный номер',
        blank=True,
        null=True
    )

    con_number = models.CharField(
        max_length=100,
        verbose_name = 'con_number?',
        blank=True,
        null=True
    )

    documents = models.CharField(
        max_length=300,
        verbose_name = 'Документы',
        blank=True,
        null=True
    )

    addr_NPA = models.CharField(
        max_length=300,
        verbose_name = 'Адрес в соответствии с НПА',
        blank=True,
        null=True
    )


    municipality = models.ForeignKey(
        Municipality, 
        on_delete=models.SET_NULL, 
        verbose_name='Муниципальное образование',
        blank=True,
        null=True
    )
    
    locality = ChainedForeignKey(
        Locality, 
        verbose_name='Населенный пункт',
        chained_field='municipality',
        chained_model_field='municipality',
        show_all=False,
        auto_choose=True,
        sort=True,
        on_delete=models.SET_NULL, 
        blank=True,
        null=True,
    )
    
    YES = 'Да'
    NO = 'Нет'
    IN_WORK = 'На подготовке'
    
    information_CHOICES = (
        (YES, 'Да'),
        (NO, 'Нет'), 
        (IN_WORK, 'На подготовке')
    )
    like_BOOLEAN = (
        (YES, 'Да'),
        (NO,  'Нет'),
    )

    OKN_in_ensemble = models.CharField(
        verbose_name='ОКН входит в ансамбль (да/нет)',
        choices=like_BOOLEAN,
        blank=True,
        null=True,
        max_length=10
     
    )
  

    information_sign = models.CharField(
        choices=information_CHOICES, 
        max_length=5,
        verbose_name='Наличие уcтановленной информационной надписи установленного образца',
        blank=True,
        null=True
    ) 
    information_sign_photo = models.ImageField(
        upload_to=image_folder, 
        blank=True,
        null=True,
        verbose_name='Фотография информационной надписи',

    )
    information_sign_conformity = models.CharField(
        verbose_name='Наличие информационной надписи, но не соответствующей требованиям',
        blank=True,
        null=True,
        choices=like_BOOLEAN,
        max_length=10

        
    )
    photo = models.ImageField(
        upload_to=image_folder, 
        blank=True,
        verbose_name='Фото',
        null=True
        

    )
    url = models.CharField(
        max_length=200,
        verbose_name='URL адрес',
        blank=True,
        null=True
        
    )
    description = models.TextField(
        verbose_name='Описание',
        blank=True,
        null=True
    )
    affiliation_U = models.CharField(
        choices=like_BOOLEAN,
        verbose_name='Принадлежность к ЮНЭСКО',
        blank=True,
        null=True,
        max_length=10
        
    )
    esp_valuable_object = models.CharField(
        choices=like_BOOLEAN,
        verbose_name='Особо ценный объект',
        blank=True,
        null=True,
        max_length=10
        
    )
    requisites_and_title = models.TextField(
        verbose_name=' Реквизиты и наименование акта органа государственной власти о постановке на государственную охрану объекта культурного наследия',
        blank=True,
        null=True
    )
    owner = models.CharField(
        max_length=200,
        verbose_name='Собственник',
        blank=True,
        null=True
    )
    management = models.CharField(
        max_length=200,
        verbose_name='Под чьим управлением',
        blank=True,
        null=True
    )
    owner_contacts = models.TextField(
        verbose_name='Контактные данные собственника ОКН',
        blank=True,
        null=True
    )
    has_security_obligation = models.CharField(
        choices=information_CHOICES, 
        max_length=5,
        verbose_name='Наличие охранного обязательства ОКН',
        blank=True,
        null=True
    )
    has_passport_OKN = models.CharField(
        choices=information_CHOICES, 
        max_length=5,
        verbose_name='Наличие паспорта ОКН',
        blank=True,
        null=True
    )
    actual_address = models.TextField(
        verbose_name='Актуальный адрес',
        blank=True,
        null=True
    )
    gen_species_appearance = models.ForeignKey(
        Species, 
        on_delete=models.SET_NULL,
        verbose_name='Общая видовая принадлежность',
        blank=True,
        null=True
    )
    has_docs_boundaries = models.CharField(
        choices=like_BOOLEAN,
        verbose_name='Наличие документов о границах территории ОКН',
        blank=True,
        null=True,
        max_length=10
    )
    req_of_approval = models.TextField(
        verbose_name='Реквизиты об утверждении границ территории',
        blank=True,
        null=True
        
    )
    has_docs_of_aprroval = models.CharField(
        verbose_name='Наличие документов об утвержденых зонах охраны',
        blank=True,
        null=True,
        max_length=10,
        choices=like_BOOLEAN
    )
    document_on_approved_security = models.TextField(
        verbose_name='Документ об утвержденых зонах охраны',
        blank=True,
        null=True
    )
    has_rights = models.CharField(
        verbose_name='Наличие зарегистрированных прав/обременений',
        blank=True,
        null=True,
        max_length=10,
        choices=like_BOOLEAN
    )
    date = models.DateField(
        verbose_name='Дата',
        blank=True,
        null=True
    )

    def __str__(self):
        return self.nativeName

pre_save.connect(create_object_info_slug, sender=ObjectInfo)


def photo_path(instance, filename):
    filename = instance.objectinfo.slug + '.' + filename.split('.')[1]

dashboard/forms.py
from django import forms
from .models import ObjectInfo
from django.contrib.admin import widgets
from . import models

class LoginForm(forms.Form):

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class ObjectInfoForm(forms.ModelForm):

    '''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].widget = widgets.AdminDateWidget()
    '''


    class Meta:
        model = ObjectInfo
        fields = '__all__'
        exclude = ('slug',)
        widgets = {
            'date': forms.DateInput(attrs={'class': 'datepicker'}),
        }




dashboard/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http.response import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework import viewsets


from .models import ObjectInfo, Municipality, Locality, Species, CategoryType, ObjectType
from .models import Image
from .serializers import ObjectInfoSerializer
from .serializers import MunicipalitySerializer
from .serializers import LocalitySerializer
from .serializers import ObjectTypeSerializer
from .serializers import CategoryTypeSerializer
from .serializers import SpeciesSerializer
from .serializers import ImageSerializer


import json


@csrf_exempt
def feedback(request):
    print(request.POST)
    if request.method == 'POST':
        contactName = request.POST.get('contactName')
        print(contactName)
        for f in request.FILES.getlist('fileFF[]'):
            print(f)
    return HttpResponse("OK")


def contact(request, id):
    context = {'id' : id}
    return render(request, 'dashboard/contact.html', context)

def home(request):
    return redirect(reverse('panel'))

def about(request):
    bread = ['О портале']
    context = {'bread': bread}
    return render(request, 'dashboard/about.html', context)


def panel(request):
    bread = ['Данные']
    return render(request, 'dashboard/panel.html', {'bread': bread})




def more_information_view(request, id):
    data = ObjectInfo.objects.get(id=id)
    print(data.__dict__)
    print('_______')
    for key in data.__dict__:
        print(data.__dict__[key])
        if data.__dict__[key] is 'None':
            print(data.__dict__[key])
            data.__dict__[key] = ''
    #print(data.__dict__)
    context = {'data': data}
    return render(request, 'dashboard/more_information.html', context)



def get_id_data(request):
    id = request.GET.get('id_row')
    row = ObjectInfo.objects.get(id=id)
    data = serializers.serialize("json", [row, ])
    struct = json.loads(data)
    data = json.dumps(struct[0])
    return HttpResponse(data)




#тестовое ajax заполнение населенных пунктов в зависимости от муниципального образования для фильтра
@csrf_exempt
def search_ajax(request):    
    response = []
    print(request.GET)
    if "search_id" in request.GET:
        search_id = request.GET['search_id']
        print("search_id={}".format(search_id))
    else:
        print('problems')
        return HttpResponse(json.dumps(response))

    localities = Locality.objects.filter(municipality_id=search_id)
    
    real_locality_ids = ObjectInfo.objects.exclude(locality_id=None).values('locality_id')
    ids_set = set(z['locality_id'] for z in real_locality_ids)
    print("Len = {}".format(len(ids_set)))
    
    for item in localities:
        if item.id in ids_set:
            response.append({'id': item.id, 'name': item.name})
    
    return HttpResponse(json.dumps(response))

# FOR NEW REST API CODE


class ObjectInfoViewSet(viewsets.ModelViewSet):
    queryset = ObjectInfo.objects.all()
    serializer_class = ObjectInfoSerializer

class MunicipalityViewSet(viewsets.ModelViewSet):
    queryset = Municipality.objects.all()
    serializer_class = MunicipalitySerializer

class LocalityViewSet(viewsets.ModelViewSet):
    queryset = Locality.objects.all()
    serializer_class = LocalitySerializer

class CategoryTypeViewSet(viewsets.ModelViewSet):
    queryset = CategoryType.objects.all()
    serializer_class = CategoryTypeSerializer

class ObjectTypeViewSet(viewsets.ModelViewSet):
    queryset = ObjectType.objects.all()
    serializer_class = ObjectTypeSerializer

class SpeciesViewSet(viewsets.ModelViewSet):
    queryset = Species.objects.all()
    serializer_class = SpeciesSerializer

class ImageViewSet(viewsets.ModelViewSet):
    queryset = Image.objects.all()
    serializer_class = ImageSerializer

templates/dashboard/about.html
{% extends "base.html" %}

{% block content %}
    <div class='container'>
        <div class='row'>
        <div style='width:100%; margin-bottom:30px;'>
        {% if bread %}
        <span style='margin-right:10px;'><a href='' style='color:#787878'>Главная</a></span><span style='margin-right:10px;'><img src="http://127.0.0.1:8000/media/img/arrow_right.png"></span>
        <span style='margin-right:10px;'><a href='' style='color:#787878'>Открытые данные</a></span><span style='margin-right:10px;'><img src="http://127.0.0.1:8000/media/img/arrow_right.png"></span>
            {% for item in bread %}
                <span style='margin-right:10px;'><a href=''>{{item}}</a></span><span style='margin-right:10px;'>
            {% endfor %}
        {% endif %}
        </div>
            <div class='col'>
                <h1>О портале</h1>
                <hr>
                <div>
                    <p>Some text...</p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/dashboard/add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col">
            <h3>Form</h3>
            {{text|safe}}
            <hr>
            <form enctype="multipart/form-data" action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary">Add</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block jquery %}
<script>
  $(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "1940:2100",
      // You can put more options here.
      dateFormat: 'yy-mm-dd',
    });
  });
</script>
{% endblock %}

templates/dashboard/contact.html
{% extends "base.html" %}

{% block content %}
    <div class='container' >
        <div class='row'>
        {{ id }}
        </div>
    </div>
{% endblock content %}

templates/dashboard/home.html
{% extends 'base.html' %}

{% block content %}
    {{ text }}
    <a href="{% url 'logout' %}">Logout</a>
{% endblock %}

templates/dashboard/jq_code_update_form.html
<script>
  $(".id_data").on('click', function(){
    var id_row = $(this).attr("data-id")
    console.log(id_row)

    data = {
      'id_row': id_row,
    }
    $.ajax({
      type: "GET",
      url: "{% url 'get_id_data'%}",
      data: data,
      dataType: "json",
      success: function(data){
      console.log("This is id data")
        console.log(data)
        console.log(data.fields.nativeName)
        $("#id_row_data").val(data.pk)
        $("#id_slug").val(data.fields.slug)
        $("#id_id_openData").val(data.fields.id_openData)
        $("#id_nativeName").val(data.fields.nativeName)
        $("#id_fullAddress").html(data.fields.fullAddress)
        $("#id_municipality").val(data.fields.municipality)
        $("#id_locality").val(data.fields.locality)


        $("#id_OKN_in_ensemble").val(data.fields.OKN_in_ensemble);

        $("#id_information_sign").val(data.fields.information_sign)

        $("#id_information_sign_photo").attr('src', data.fields.information_sign_photo);

        $("#id_information_sign_conformity").val(data.fields.information_sign_conformity)


        //$("#id_photo").val(data.fields.photo)
        $("#id_url").val(data.fields.url)
        $("#id_description").val(data.fields.description)


          $("#id_affiliation_U").val(data.fields.affiliation_U);


        $("#id_esp_valuable_object").val(data.fields.esp_valuable_object);



        $("#id_requisites_and_title").html(data.fields.requisites_and_title)
        $("#id_owner").val(data.fields.owner)
        $("#id_management").val(data.fields.management)
        $("#id_owner_contacts").val(data.fields.owner_contacts)
        $("#id_has_security_obligation").val(data.fields.has_security_obligation)
        $("#id_has_passport_OKN").val(data.fields.has_passport_OKN)
        $("#id_actual_address").val(data.fields.actual_address)
        $("#id_gen_species_appearance").val(data.fields.gen_species_appearance)
        $("#id_req_of_approval").html(data.fields.req_of_approval)


        $("#id_has_docs_boundaries").val(data.fields.has_docs_boundaries);



        $("#id_has_docs_of_aprroval").val(data.fields.has_docs_of_aprroval);


        $("#id_document_on_approved_security").val(data.fields.document_on_approved_security);


        $("#id_has_rights").val(data.fields.has_rights);


        $("#id_date").val(data.fields.date)
        console.log("Hello world")
      }
    })
  })
</script>

templates/dashboard/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <br>
    <br>
    <br>
    <br>
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">login</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</div>


{% endblock %}

templates/dashboard/more_information.html
{% extends 'base.html' %}




{%block title%}{{data.nativeName}}{%endblock%}

{%block content%}



<script type="text/javascript">

var id = {{ data.id}}

$(document).ready(function(){
            console.log(id)
             
         //    var id = e.relatedTarget.dataset.id;
             const url = '/api/objects/'+id;
             $("#my_slider_id").empty();
             $.getJSON(url, function (data) {
                 if((data.nativeName!==null)&&(data.nativeName!=='None')) { 
                     $('#modal_nativeName').text(data.nativeName);  
                     $('#exampleModalLabel').text(data.nativeName);  
                 } else {
                     $('#modal_nativeName').text('');
                     $('#exampleModalLabel').text('');  
                 }
                 if((data.fullAddress!==null)&&(data.fullAddress!=='None')) { $('#modal_fullAddress').text(data.fullAddress);
                 } else {
                     $('#modal_fullAddress').text('');
                 }
                 if((data.municipality!==null)&&(data.municipality!=='None')) { $('#modal_municipality').text(data.municipality.name);
                 } else {
                     $('#modal_municipality').text('');
                 }
                 if((data.locality!==null)&&(data.locality!==null)) { $('#modal_locality').text(data.locality.name);  
                 }else {
                     $('#modal_locality').text('');
                 }
                 if(data.images.length>0){
                    for(key in data.images) {
                        console.log(data.images[key]);
                        $('#my_slider_id').
                            append("<a href='/media/" + data.images[key]+
                                   "' ><img src='/media/"+data.images[key]+
                                   "' style='width:100px; padding-left:5px'></a>");
                    
                    }
          
                 } else {
                    //   $('#modal_photo').attr('src', "/media/img/noImage.png");
                    //   $('#img_ref').attr('href', "/media/img/noImage.png");
                    $('#my_slider_id').
                    append("<img src='/media/img/noImage.png' style='width:100px;'></img>");
                  
                 }
                 if((data.description!==null)&&(data.description!=='None')) { $('#modal_description').text(data.description);  
                 } else {
                     $('#modal_description').text('');
                 }
                 if((data.affiliation_U!==null)&&((data.affiliation_U!=='None'))) { $('#modal_affiliation_U').text(data.affiliation_U);
                 } else {
                     $('#modal_affiliation_U').text('');
                 }
                 if((data.esp_valuable_object!==null)&&(data.esp_valuable_object!=='None')) { $('#modal_esp_valuable_object').text(data.esp_valuable_object);
                 } else {
                     $('#modal_esp_valuable_object').text('');
                 }
                 if((data.requisites_and_title!==null)&&(data.requisites_and_title!=='None')) { $('#modal_requisites_and_title').text(data.requisites_and_title); 
                 } else {
                     $('#modal_requisites_and_title').text('');
                 }
                 if((data.gen_species_appearance!==null)&&(data.gen_species_appearance!==null)) { $('#modal_gen_species_appearance').text(data.gen_species_appearance.name); 
                 } else {
                     $('#modal_gen_species_appearance').text('');
                 }
                 if((data.category_type!==null)&&(data.category_type!==null)) { $('#modal_category_type').text(data.category_type.name); 
                 } else {
                     $('#modal_category_type').text('');
                 }
                 if((data.reg_number!==null)&&(data.reg_number!==null)) { $('#modal_reg_number').text(data.reg_number); 
                } else {
                    $('#modal_reg_number').text('');
                }
                if((data.documents!==null)&&(data.documents!==null)) { 
                    $('#modal_documents').text(data.documents);
                    $('#modal_documents').attr("href", data.documents); 
                } else {
                    $('#modal_documents').text('');
                }
                $('#modal_url').text('http://www.oknrd.ru/objects/'+data.id)
                $('#modal_url').attr('href', '/objects/'+data.id)

             })

});
</script>


<div class="container" id="more_information">
        <div class="col-12" >
          
            <table class="table_more_information">
                <tr>
                    <td  style="width:40%">Наименование:</td>
                    <td  style="width:60%; text-align: right;" id='modal_nativeName'></td>
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>
                <tr>
                    <td>Полный адрес:</td>
                    <td id='modal_fullAddress' style="width:60%; text-align: right;"></td>
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>
                <tr>
                    <td>Муниципальное образование:</td>
                    <td id='modal_municipality' style="width:60%; text-align: right;"></td>
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>
                <tr>
                    <td>Населенный пункт:</td>
                    <td id='modal_locality' style="width:60%; text-align: right;"></td>
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>
               
                <tr>
                    <td>Фото:</td>
                    <td style="width:60%; text-align: right;">
                        <div class='my-slider' id='my_slider_id' style="white-space:nowrap; overflow-x:auto; width:560px; margin-right:0px" >
                            
                        </div>
                    </td>
                    
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>
               
                <tr>
                    <td>Описание:</td>
                    <td id='modal_description' style="width:60%; text-align: right;"></td>
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>
                <tr>
                    <td>Принадлежность к ЮНЭСКО:</td>
                    <td id='modal_affiliation_U' style="width:60%; text-align: right;"></td>
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>
                <tr>
                    <td>Особо ценный объект:</td>
                    <td id='modal_esp_valuable_object' style="width:60%; text-align: right;"></td>
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>
                <tr>
                    <td>Реквизиты и наименование акта органа государственной власти о постановке на государственную охрану объекта культурного наследия:</td>
                    <td id='modal_requisites_and_title' style="width:60%; text-align: right;"></td>
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>
               
                <tr>
                    <td>Общая видовая принадлежность:</td>
                    <td id='modal_gen_species_appearance' style="width:60%; text-align: right;"></td>
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>

                <tr>
                    <td>Категория объекта:</td>
                    <td id='modal_category_type' style="width:60%; text-align: right;"></td>
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>

                <tr>
                    <td>Регистрационный номер ЕГОКН:</td>
                    <td id='modal_reg_number' style="width:60%; text-align: right;"></td>
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>

                <tr>
                    <td>Документ:</td>
                    <td  style="width:60%; text-align: right;"><a id='modal_documents' href='#'></a></td>
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>

                <tr>
                    <td>Постоянный  URL:</td>
                    <td  style="width:60%; text-align: right;"><a id='modal_url' href='#'></a></td>
                </tr>
                <tr>
                    <td colspan="2"><hr></td>
                </tr>
            </table>
            </div>
      </div>
 {%endblock%}